<div class="container">
    <h3><i class="fa fa-cogs"></i> Space Database</h3>
    <!-- Show Flash Session Data -->
    <p><?= $this->flashSession->output() ?></p>

    <?php
        # Check User Login
        if ($this->session->has('IS_LOGIN'))
        {
            echo $this->tag->linkTo([
                "space/create", 
                '<i class="fa fa-plus" aria-hidden="true"></i> Add Space <span class="sr-only">(current)</span>', 
                "class" => "nav-link"]
            );
        }
    ?>

    <!-- Check User Spaces Found/NotEmpty -->
    <?php if (!empty($spacesData->count())) { ?>
        <table class="table table-hover table-sm table-bordered">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tower ID</th>
                    <th scope="col">Project Table ID</th>
                    <th scope="col">Leg</th>
                    <th scope="col">Height</th>
                    <th scope="col">Merk</th>
                    <th scope="col">Berat</th>
                    <th scope="col">Diameter</th>
                </tr>
            </thead>
            <tbody>
                    <?php foreach ($spacesData as $key => $space) { ?>
                        <tr>
                            <th scope="row"><?= ++$key ?></th>
                            <td><?= $space->tower_id ?></td>
                            <td><?= $space->project_table_id ?></td>
                            <td><?= $space->leg ?></td>
                            <td><?= $space->height ?></td>
                            <td><?= $space->merk ?></td>
                            <td><?= $space->berat ?></td>
                            <td><?= $space->diameter ?></td>
                            <td>
                                <?php
                                    $space_id = str_replace(array("'",'%'),array('%27',"'"),urlencode($this->crypt->encryptBase64($space->space_id)));
                                    echo $this->tag->linkTo([
                                        "space/edit/".$space_id,
                                        '<i class="fa fa-pencil"></i>',
                                        "class" => "btn btn-primary",
                                        "title" => "Edit Space"
                                    ]);
                                    echo "&nbsp";
                                    echo $this->tag->linkTo([
                                        "space/delete/".$space_id,
                                        '<i class="fa fa-trash"></i>',
                                        "class" => "btn btn-danger",
                                        "onclick" => "return confirm('Are you sure?')",
                                        "title" => "Delete Space"
                                    ]);
                                ?>
                            </td>
                        <tr>
                    <?php } ?>
            </tbody>
        </table>
    <?php } else { ?>
        <hr>
        <div class="text-center">
            <i class="fa fa-database fa-5x text-danger" aria-hidden="true"></i>
            <h2 class="text-danger"><b>Sorry,</b> No Data Found!</h2>
            <?php
                echo $this->tag->linkTo([
                    "space/create",
                    'create new space',
                ]);
            ?>
        </div>
    <?php } ?>
</div>