<div class="container">
    <h3><i class="fa fa-cogs"></i> Project Database</h3>
    <!-- Show Flash Session Data -->
    <p><?= $this->flashSession->output() ?></p>

    <?php
        # Check User Login
        if ($this->session->has('IS_LOGIN'))
        {
            echo $this->tag->linkTo([
                "project/create", 
                '<i class="fa fa-plus" aria-hidden="true"></i> Add Project <span class="sr-only">(current)</span>', 
                "class" => "nav-link"]
            );
        }
    ?>

    <!-- Check User Projects Found/NotEmpty -->
    <?php if (!empty($projectsData->count())) { ?>
        <table class="table table-hover table-sm table-bordered">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tower ID</th>
                    <th scope="col">Project ID</th>
                    <th scope="col">Portofolio</th>
                    <th scope="col">Ubis</th>
                    <th scope="col">Plan Group</th>
                    <th scope="col">User Stat Lv 1</th>
                    <th scope="col">User Stat Lv 2</th>
                    <th scope="col">Nama Tenant</th>
                </tr>
            </thead>
            <tbody>
                    <?php foreach ($projectsData as $key => $project) { ?>
                        <tr>
                            <th scope="row"><?= ++$key ?></th>
                            <td><?= $project->tower_id ?></td>
                            <td><?= $project->project_id ?></td>
                            <td><?= $project->portofolio ?></td>
                            <td><?= $project->ubis ?></td>
                            <td><?= $project->plan_group ?></td>
                            <td><?= $project->user_stat_lv_1 ?></td>
                            <td><?= $project->user_stat_lv_2 ?></td>
                            <td><?= $project->nama_tenant ?></td>
                            <td>
                                <?php
                                    $project_table_id = str_replace(array("'",'%'),array('%27',"'"),urlencode($this->crypt->encryptBase64($project->project_table_id)));
                                    echo $this->tag->linkTo([
                                        "project/edit/".$project_table_id,
                                        '<i class="fa fa-pencil"></i>',
                                        "class" => "btn btn-primary",
                                        "title" => "Edit Project"
                                    ]);
                                    echo "&nbsp";
                                    echo $this->tag->linkTo([
                                        "project/delete/".$project_table_id,
                                        '<i class="fa fa-trash"></i>',
                                        "class" => "btn btn-danger",
                                        "onclick" => "return confirm('Are you sure?')",
                                        "title" => "Delete Project"
                                    ]);
                                ?>
                            </td>
                        <tr>
                    <?php } ?>
            </tbody>
        </table>
    <?php } else { ?>
        <hr>
        <div class="text-center">
            <i class="fa fa-database fa-5x text-danger" aria-hidden="true"></i>
            <h2 class="text-danger"><b>Sorry,</b> No Data Found!</h2>
            <?php
                echo $this->tag->linkTo([
                    "project/create",
                    'create new project',
                ]);
            ?>
        </div>
    <?php } ?>
</div>