<div class="container">
    <h3><i class="fa fa-cogs"></i> Tower Database</h3>
    <!-- Show Flash Session Data -->
    <p><?= $this->flashSession->output() ?></p>

    <?php
        # Check User Login
        if ($this->session->has('IS_LOGIN'))
        {
            echo $this->tag->linkTo([
                "tower/create", 
                '<i class="fa fa-plus" aria-hidden="true"></i> Add Tower <span class="sr-only">(current)</span>', 
                "class" => "nav-link"]
            );
        }
    ?>

    <!-- Check User Towers Found/NotEmpty -->
    <?php if (!empty($towersData->count())) { ?>
        <table class="table table-hover table-sm table-bordered">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Site ID</th>
                    <th scope="col">Site Name</th>
                    <th scope="col">Site Type</th>
                    <th scope="col">Regional</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Kota/Kab.</th>
                    <th scope="col">Leg</th>
                    <th scope="col">Height</th>
                </tr>
            </thead>
            <tbody>
                    <?php foreach ($towersData as $key => $tower) { ?>
                        <tr>
                            <th scope="row"><?= ++$key ?></th>
                            <td><?= $tower->site_id_dmt ?></td>
                            <td><?= $tower->site_name ?></td>
                            <td><?= $tower->site_type ?></td>
                            <td><?= $tower->regional ?></td>
                            <td class="text-truncate" style="max-width: 350px;"><?= $tower->alamat_act ?></td>
                            <td><?= $tower->kota_kabupaten ?></td>
                            <td><?= $tower->tower_leg ?></td>
                            <td><?= $tower->tower_height ?></td>
                            <td>
                                <?php
                                    $tower_id = str_replace(array("'",'%'),array('%27',"'"),urlencode($this->crypt->encryptBase64($tower->tower_id)));
                                    echo $this->tag->linkTo([
                                        "tower/edit/".$tower_id,
                                        '<i class="fa fa-pencil"></i>',
                                        "class" => "btn btn-primary",
                                        "title" => "Edit Tower"
                                    ]);
                                    echo "&nbsp";
                                    echo $this->tag->linkTo([
                                        "tower/delete/".$tower_id,
                                        '<i class="fa fa-trash"></i>',
                                        "class" => "btn btn-danger",
                                        "onclick" => "return confirm('Are you sure?')",
                                        "title" => "Delete Tower"
                                    ]);
                                ?>
                            </td>
                        <tr>
                    <?php } ?>
            </tbody>
        </table>
    <?php } else { ?>
        <hr>
        <div class="text-center">
            <i class="fa fa-database fa-5x text-danger" aria-hidden="true"></i>
            <h2 class="text-danger"><b>Sorry,</b> No Data Found!</h2>
            <?php
                echo $this->tag->linkTo([
                    "tower/create",
                    'create new tower',
                ]);
            ?>
        </div>
    <?php } ?>
</div>